### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JaviBecerra**
This pull request incorporates the following features to profiletool:
-Add a new selection mode "Selected layer", which allows profiling all the features in a layer (instead of the single feature of the standard "selected polyline" mode).
-Add a checkbox to activate/deactivate interpolation of profiles along the polyline (i.e. show only values at the polyline vertices when interpolation is not activated).
-Allow selection of slope profiles (in percentage and degrees) in addition to the standard height profile.
-Profile is now automatically updated in interactive mode with each new point added to the rubber band.

### CODE REVIEW

**Comment by JaviBecerra** [comment]
Hi,
Can any of the maintainers have a look at this?
I guess we may have made a changeset too big for a single pull request, we will gladly take any suggestions on how we can help to get this reviewed/merged.

**Comment by etiennesky** [comment]
Hi I am sorry for not responding sooner. I am no longer working actively on QGis, but I can try to have a look at the code and see if it is ok to merge. 

It would be easier if you could add each enhancement as a separate merge request.

Could you provide some test dataset with many features?

**Comment by JaviBecerra** [comment]
Hi Etienne,

It's ok, no need to excuse yourself.

I will take a look back and churn it into two or three smaller/cleaner 
merge requests. Will also check for a test dataset. When you talk about 
many features, what scale do you have in mind? Tens, hundreds, thousands...?

Thanks for taking the time to check it, and for all the hard work you've 
put in the plugin.

**Comment by etiennesky** [comment]
Hi, I that a test dataset with about 10 features or less should be sufficient.

**Comment by JaviBecerra** [comment]
Closed as this pull request is being replaced by a different request per implemented feature.

**Pull request closed without merging**
